# see https://goreleaser.com
project_name: apigear
before:
  hooks:
    - go mod tidy
    - go generate ./...
release:
  github:
    owner: apigear-io
    name: cli-releases
  discussion_category_name: General
builds:
  - id: apigear
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: "386"
    main: cmd/apigear/main.go
    binary: apigear
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
checksum:
  name_template: "checksums.txt"
archives:
  - id: zip
    format: zip
  - id: binary
    format: binary
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: apigear
    ids:
      - zip
    tap:
      owner: apigear-io
      name: homebrew-tap
    folder: Formula
