name: release

on:
  pull_request:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: check go version
        run: go version
