name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

# See https://github.com/mvdan/github-actions-golang/blob/master/README.md#how-do-i-install-private-modules

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - run: go test ./...
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.APIGEAR_REPOS }}
