name: release

on:
  push:
    tags:
      - "*"

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/apigear-io/*"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git config --global url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - run: go test ./...
  test-macos:
    runs-on: macos-latest
    env:
      GOPRIVATE: "github.com/apigear-io/*"
      GITHUB_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
    steps:
      - run: git config --global url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - run: go test ./...
  test-windows:
    env:
      GOPRIVATE: "github.com/apigear-io/*"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: windows-latest
    steps:
      - run: git config --global url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - run: go test ./... -tags windows_test
  release:
    needs: [test-ubuntu, test-macos, test-windows]
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/apigear-io/*"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git config --global url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: run all tests
        run: go test ./...
      - name: run go releaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
