name: release

on:
  push:
    tags:
      - "*"
# See https://github.com/mvdan/github-actions-golang/blob/master/README.md#how-do-i-install-private-modules

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
  GOPRIVATE: "github.com/apigear-io/*"
  GH_ACCESS_TOKEN: ${{ secrets.APIGEAR_REPOS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - run: git config --global url.https://jryannel:$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - run: go test ./...
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - run: git config --global url.https://jryannel:$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - run: go test ./... -tags windows_test
  release:
    needs: [test-macos, test-windows]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - run: git config --global url.https://jryannel:$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: run all tests
        run: go test ./...
      - name: run go releaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
