# run on all pushes (but not push tags)
# see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs

on:
  pull_request:
    branches:
      - main

name: tests
# tests for all push and pull requests
# tests only on linux, for release we test on linux and macos, windows

env:
  GOPRIVATE: "github.com/apigear-io/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24.x"
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - run: go test ./...
